export const publicationContract = {
  runtimeExports: {
    stable: [
      "createResolvedStoreHooks",
      "createShallowStore",
      "createStoreProvider",
      "createStoreToolkit",
    ],
    deprecated: [],
  },
  typeExports: {
    stable: [
      "GlobalStoreBindings",
      "MutatorsStateCreator",
      "ResolvedStoreBindings",
      "ShallowStoreBindings",
      "SimpleStateCreator",
      "StoreApiWithMutators",
      "StoreMutatorTuple",
      "StorePlainHook",
      "StoreProviderConfig",
      "StoreProviderProps",
      "StoreProviderResult",
      "StoreRecipe",
      "StoreToolkit",
      "StoreToolkitOptions",
      "StoreValueHook",
    ],
    deprecated: [],
  },
  packedFiles: [
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "dist/index.cjs",
    "dist/index.cjs.map",
    "dist/index.d.cts",
    "dist/index.d.ts",
    "dist/index.js",
    "dist/index.js.map",
    "package.json",
  ],
  runtimeDependencies: ["@okyrychenko-dev/type-utils"],
  peerDependencies: {
    react: "^18.0.0 || ^19.0.0",
    zustand: "^5.0.0",
  },
  exportTargets: ["./dist/index.d.ts", "./dist/index.js", "./dist/index.d.cts", "./dist/index.cjs"],
  sideEffects: false,
};
